### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by er** [5tanly/FactionTop#1]
Wasn't sure where to ask for your discord as I couldn't find it in any of your scripts, could you give me it so I can ask a few questions regarding the discord webhook post request? I tried to use it in one of my scripts (for baltop rather than f top) but was getting an error with the request.

**Comment by 5tanly** [comment]
Of course you would be getting an error if you just changed the command to /baltop because the two commands output very different data. My discord is Stan#8034.

**Comment by er** [comment]
I didn't just change the command, I did account for the different data and different format. I believe the error I'm having is more with the HTTP request, sent you a friend request.
